# Generated by Django 3.2.15 on 2022-10-03 12:15

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211107_1454'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
