# Generated by Django 3.2.15 on 2022-10-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_feed_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
