# Generated by Django 3.2.15 on 2022-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_feed_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleteReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField(default=0)),
            ],
        ),
    ]
